from fastapi import FastAPI
from pydantic import BaseModel
from typing import List
import time
import random

# --- 1. Define the Core Data Structure (The API Contract) ---
# This schema uses Pydantic to ensure all data served by the AI is correctly typed.
class SecurityAlert(BaseModel):
    """
    Schema for a unified, predictive security alert generated by the GNN fusion engine.
    """
    alert_id: str
    timestamp: float = time.time()
    latitude: float
    longitude: float
    risk_score: float  # 0.0 (Low) to 1.0 (Critical)
    threat_type: str   # e.g., "Cross-Border Infiltration", "Civil Unrest", "Misinformation"
    source_type: str   # e.g., "Satellite + Social", "Social Media Only", "Satellite Only"
    recommended_action: str
    peace_module_flag: bool  # True if Civic Peace Module recommends de-escalation

# --- 2. Initialize FastAPI Application ---
app = FastAPI(
    title="UlinziMind AI Sentinel API",
    description="Real-time predictive intelligence for National Security.",
    version="1.0.0"
)

# --- 3. Mock Data Generation Endpoint (For MVP Prototyping) ---
# This endpoint generates sample alerts until your real AI models are ready.
@app.get("/api/v1/alerts", response_model=List[SecurityAlert])
def get_realtime_alerts(count: int = 5):
    """
    Generates a list of mock Security Alerts for real-time dashboard display.
    In the final system, this would call the GNN model inference.
    """
    alerts = []
    # Geo-boundaries for a large area in Kenya (Example: near Nairobi/Kiambu area)
    min_lat, max_lat = -2.0, 1.0
    min_lon, max_lon = 36.0, 40.0

    threats = ["Civil Unrest", "Misinformation", "Cross-Border Infiltration", "Illegal Gathering"]
    actions = ["Issue de-escalation guidance", "Monitor satellite area X", "Verify source on platform Y"]

    for i in range(count):
        risk = round(random.uniform(0.5, 0.95), 2)
        alert = SecurityAlert(
            alert_id=f"UM-{int(time.time() * 1000)}-{i}",
            latitude=round(random.uniform(min_lat, max_lat), 4),
            longitude=round(random.uniform(min_lon, max_lon), 4),
            risk_score=risk,
            threat_type=random.choice(threats),
            source_type=random.choice(["Satellite + Social", "Social Media Only"]),
            recommended_action=random.choice(actions),
            peace_module_flag=(risk < 0.7) # Assume lower risk triggers peace flag
        )
        alerts.append(alert)
    
    return alerts

# --- 4. Root Endpoint (Welcome Message) ---
@app.get("/")
def read_root():
    return {"message": "UlinziMind API is running. Go to /docs for API documentation."}