from fastapi import FastAPI
from pydantic import BaseModel
from typing import List
import time
import random

# NEW: Import CORS middleware
from fastapi.middleware.cors import CORSMiddleware 

# FIX: Changed to an absolute import to resolve the 'ImportError' when running uvicorn directly.
from ai_core import UlinziMindEngine 

# --- 1. Define the Core Data Structure (The API Contract) ---
class SecurityAlert(BaseModel):
    """
    Schema for a unified, predictive security alert generated by the GNN fusion engine.
    """
    alert_id: str
    timestamp: float = time.time()
    latitude: float
    longitude: float
    risk_score: float  # 0.0 (Low) to 1.0 (Critical)
    threat_type: str   # e.g., "Cross-Border Infiltration", "Civil Unrest", "Misinformation"
    source_type: str   # e.g., "Satellite + Social", "Social Media Only", "Satellite Only"
    recommended_action: str
    peace_module_flag: bool  # True if Civic Peace Module recommends de-escalation

# --- 2. Initialize FastAPI Application and CORS ---
app = FastAPI(
    title="UlinziMind AI Sentinel API",
    description="Real-time predictive intelligence for National Security.",
    version="1.0.0"
)

# CORS Middleware Configuration (Necessary for React frontend)
origins = [
    "http://127.0.0.1:5173",  
    "http://localhost:5173",  
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize the AI Engine globally (Run only once at startup)
try:
    ai_engine = UlinziMindEngine()
except ImportError as e:
    print(f"FATAL: Cannot initialize UlinziMindEngine due to missing AI dependencies. Error: {e}")
    ai_engine = None


# --- 3. AI-Driven Data Generation Endpoint ---
@app.get("/api/v1/alerts", response_model=List[SecurityAlert])
def get_realtime_alerts(count: int = 5):
    """
    Generates a list of Security Alerts using the UlinziMind AI Engine's logic.
    This endpoint fetches real data (or stub data if dependencies are missing).
    """
    if not ai_engine:
        # Fallback if engine failed to initialize
        return [] 
        
    alerts = []
    
    # FIX: Geo-boundaries cover the entire country (Monitoring focus)
    min_lat, max_lat = -4.5, 5.0 # South Coast to Ethiopia/Turkana
    min_lon, max_lon = 34.0, 42.0 # Lake Victoria/Uganda border to Somalia Coast

    for i in range(count):
        
        # 1. Define specific search coordinates/keywords for this mock instance
        # These are randomized inputs that trigger the logic in ai_core.py
        mock_geo_input = {
            'latitude': round(random.uniform(min_lat, max_lat), 4),
            'longitude': round(random.uniform(min_lon, max_lon), 4),
            'image_url': 'simulated_satellite_image_path'
        }
        
        mock_social_keywords = random.choice([
            ['unrest', 'protest'],
            ['violence', 'hate'],
            ['market', 'peace'],
            ['cross', 'border']
        ])
        
        # 2. Get data from Sentinels (uses stubs if YOLO/BERT are not installed)
        geo_data = ai_engine.geo_sentinel.process_satellite_imagery(mock_geo_input)
        social_data = ai_engine.social_sentinel.analyze_social_stream(mock_social_keywords)
        
        # 3. Fuse data and get the final prediction (mimics GNN output)
        prediction = ai_engine.fuse_and_predict(geo_data, social_data)
        
        # 4. Construct the final alert model using the AI output
        alert = SecurityAlert(
            alert_id=f"UM-AI-{int(time.time() * 1000)}-{i}",
            latitude=geo_data['geo_coordinates'][0],
            longitude=geo_data['geo_coordinates'][1],
            risk_score=prediction['risk_score'],
            threat_type=prediction['threat_type'],
            source_type=prediction['source_type'],
            recommended_action=prediction['recommended_action'],
            peace_module_flag=prediction['peace_module_flag']
        )
        alerts.append(alert)
    
    return alerts

# --- 4. Root Endpoint (Welcome Message) ---
@app.get("/")
def read_root():
    return {"message": "UlinziMind API is running. Go to /docs for API documentation."}